const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Mapa: 0},
	{Sólido: 0},
	{chao1: 0},
	{chao2: 0},
	{Fixar: 0},
	{Ninja: 0},
	{Senóide: 0},
	{agua: 0},
	{chao3: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Ninjafundo: 0},
	{tecladoninja: 0},
	{Kunai: 0},
	{chaoalto: 0},
	{chaoalto2: 0},
	{chaolto3: 0},
	{Âncora: 0},
	{Pontos: 0},
	{limitador: 0},
	{ação: 0},
	{zombie: 0},
	{Arvore: 0},
	{lapide: 0},
	{Placa: 0},
	{Mato: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Parabens: 0},
	{Áudio: 0},
	{Vídeo: 0},
	{gameover: 0},
	{Reiniciar: 0},
	{Sprite: 0},
	{Play: 0},
	{Iniciar: 0},
	{Recomeçar: 0}
];

self.InstanceType = {
	Mapa: class extends self.ITiledBackgroundInstance {},
	chao1: class extends self.ITiledBackgroundInstance {},
	chao2: class extends self.ITiledBackgroundInstance {},
	Ninja: class extends self.ISpriteInstance {},
	agua: class extends self.ITiledBackgroundInstance {},
	chao3: class extends self.ITiledBackgroundInstance {},
	Ninjafundo: class extends self.ISpriteInstance {},
	tecladoninja: class extends self.IInstance {},
	Kunai: class extends self.ISpriteInstance {},
	chaoalto: class extends self.ISpriteInstance {},
	chaoalto2: class extends self.ISpriteInstance {},
	chaolto3: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	limitador: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	Arvore: class extends self.ITiledBackgroundInstance {},
	lapide: class extends self.ITiledBackgroundInstance {},
	Placa: class extends self.ITiledBackgroundInstance {},
	Mato: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Parabens: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	Vídeo: class extends self.IWorldInstance {},
	gameover: class extends self.ITiledBackgroundInstance {},
	Reiniciar: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Play: class extends self.ITiledBackgroundInstance {},
	Iniciar: class extends self.IButtonInstance {},
	Recomeçar: class extends self.IButtonInstance {}
}